.. -*- rst -*-

============
API versions
============




List API versions
=================

.. rest_method::  GET /versions

Shows details for the Image service API v1.


Normal response codes: 200
Error response codes:


Request
-------

.. rest_parameters:: parameters.yaml





Response Example
----------------

.. literalinclude:: ../samples/image-versions-response.json
   :language: javascript




List API versions
=================

.. rest_method::  GET /

Lists information about all Image service API versions.

Error response codes:300,


Request
-------

.. rest_parameters:: parameters.yaml






