.. -*- rst -*-

=======================================
Share export locations (since API v2.9)
=======================================

Set of APIs used for viewing export locations of shares.

By default, these APIs are admin-only. Use the ``policy.json`` file
to grant permissions for these actions to other roles.

Lists all export locations for a share.

Show details of an export location belonging to a share.

