.. -*- rst -*-

=================
Build information
=================

Shows build information for a `Senlin
<https://wiki.openstack.org/wiki/Senlin>`_ deployment.


Show build information
======================

.. rest_method::  GET /v1/build-info

Shows build information for a Senlin deployment.


Normal response codes: 200
Error response codes:


Request
-------

.. rest_parameters:: parameters.yaml





Response Example
----------------

.. literalinclude:: ../samples/build-show-response.json
   :language: javascript



