.. -*- rst -*-

============
API versions
============

Lists information for all Clustering API versions.


List versions
=============

.. rest_method::  GET /

Lists information for all Clustering API versions.


Normal response codes: 200
Error response codes:


Request
-------

.. rest_parameters:: parameters.yaml





Response Example
----------------

.. literalinclude:: ../samples/senlin-versions-list-response.json
   :language: javascript



