.. -*- rst -*-

========
Versions
========




Get version details
===================

.. rest_method::  GET /v2.0

Gets detailed information about a version of the Identity API.


Normal response codes: 200
Error response codes:203,413,405,404,403,401,400,503,


Request
-------

.. rest_parameters:: parameters.yaml



Response Parameters
-------------------

.. rest_parameters:: parameters.yaml

   - location: location



Response Example
----------------

.. literalinclude:: ../samples/admin/version-show-response.json
   :language: javascript











